# Example goseek configuration

local_dir: "/home/za27933/ray_results"
ckpt_save_freq_timesteps: 10000

env_config: {
        FILENAME: /home/za27933//tess/goseek-challenge/simulator/goseek-allscenes-v0.1.4.x86_64,
        SCENES: [1, 2, 3, 4],
        episode_length: 400,
        video_log_path: "./videos",
        collision_reward: 0,
        target_found_reward: 1,
        success_dist: 2,
        no_collisions: False,
        modalities: ["RGB", "SEGMENTATION", "DEPTH"],
        visible_targets: False,
        use_esdf_data: True,
        query_image_data: False,
        esdf_data: {'1': "/home/za27933/projects/tess/dsg-rl/data/esdf/scene_1_esdf_slices.npy",
                           '2': "/home/za27933/projects/tess/dsg-rl/data/esdf/scene_2_esdf_slices.npy",
                           '3': "/home/za27933/projects/tess/dsg-rl/data/esdf/scene_3_esdf_slices.npy",
                           '4': "/home/za27933/projects/tess/dsg-rl/data/esdf/scene_4_esdf_slices.npy",
                    },
        scene_graph: {"1": "/home/za27933/projects/tess/dsg-rl/data/dsgs/dsg_scene1.pkl",
                      "2": "/home/za27933/projects/tess/dsg-rl/data/dsgs/dsg_scene2.pkl",
                      "3": "/home/za27933/projects/tess/dsg-rl/data/dsgs/dsg_scene3.pkl",
                      "4": "/home/za27933/projects/tess/dsg-rl/data/dsgs/dsg_scene4.pkl",
                    },
    }

model: {
        custom_model: gnn_actor_critic,
        custom_model_config: {
            fields: {
                nodes: GRAPH_NODES,
                edges: GRAPH_EDGES,
                node_shapes: GRAPH_NODE_SHAPE,
                edge_shapes: GRAPH_EDGE_SHAPE,
            },
            in_features: 10,
            graph_conv_features: [64, 64, 64],
            n_layer_nodes: 8,
            embedding_size: [512],
        },
        max_seq_len: 400,
        vf_share_layers : false
    }

# training
lr : 1.0e-4
gamma : 0.99
lambda : .9
vf_loss_coeff : 0.25
clip_param : 0.3
vf_clip_param : 25
entropy_coeff : 0.01

# batch
train_batch_size : 1024 # 4096
sgd_minibatch_size : 128
num_sgd_iter : 30
rollout_fragment_length: 400

# env
env : goseek
framework : torch
num_workers : 3
num_gpus : 1
num_envs_per_worker : 1
num_gpus_per_worker: 0.25
log_level : INFO


evaluation_interval : 50
evaluation_num_episodes : 50
evaluation_num_workers: 1
evaluation_config: {
    env_config: {
            SCENES: [5],
            RANK: 3,
            FILENAME: /home/za27933/tess/goseek-challenge/simulator/goseek-allscenes-v0.1.4.x86_64,
            esdf_data: {'5': "/home/za27933/projects/tess/dsg-rl/data/esdf/scene_5_esdf_slices.npy"},
            scene_graph: {"5": "/home/za27933/projects/tess/dsg-rl/data/dsgs/dsg_scene5.pkl"},
        }
    }
